"""
Apache Virtual Host Configuration Generator

Generates valid Apache2 configuration files from structured form data.
Supports static websites, reverse proxies, and redirect-only vhosts.
"""

from datetime import datetime


def _common_directives(vhost):
    lines = []
    if vhost.error_log:
        lines.append(f'    ErrorLog {vhost.error_log}')
    if vhost.custom_log:
        lines.append(f'    CustomLog {vhost.custom_log} combined')
    return lines


def _ssl_directives(vhost):
    lines = []
    if vhost.ssl_enabled:
        lines.append('    SSLEngine on')
        if vhost.ssl_cert_file:
            lines.append(f'    SSLCertificateFile {vhost.ssl_cert_file}')
        if vhost.ssl_key_file:
            lines.append(f'    SSLCertificateKeyFile {vhost.ssl_key_file}')
    return lines


def _server_name_block(vhost):
    lines = [f'    ServerName {vhost.server_name}']
    aliases = [a.strip() for a in vhost.server_alias.split(',') if a.strip()] if vhost.server_alias else []
    if aliases:
        lines.append(f'    ServerAlias {" ".join(aliases)}')
    return lines


def generate_static_vhost(vhost):
    lines = [
        f'# Generated by apache-vhost-manager on {datetime.utcnow().isoformat()}',
        f'<VirtualHost *:{vhost.listen_port}>',
    ]
    lines.extend(_server_name_block(vhost))
    lines.append(f'    DocumentRoot {vhost.document_root}')
    lines.extend(_common_directives(vhost))
    lines.extend(_ssl_directives(vhost))

    if vhost.directory_options or vhost.allow_override or vhost.require_directive:
        lines.append(f'    <Directory {vhost.document_root}>')
        if vhost.directory_options:
            lines.append(f'        Options {vhost.directory_options}')
        if vhost.allow_override:
            lines.append(f'        AllowOverride {vhost.allow_override}')
        if vhost.require_directive:
            lines.append(f'        Require {vhost.require_directive}')
        lines.append('    </Directory>')

    if vhost.extra_directives:
        for directive in vhost.extra_directives.splitlines():
            lines.append(f'    {directive.strip()}')

    lines.append('</VirtualHost>')

    # HTTP to HTTPS redirect vhost
    if vhost.force_https and vhost.ssl_enabled:
        lines.append('')
        lines.append(f'<VirtualHost *:{vhost.listen_port}>')
        lines.extend(_server_name_block(vhost))
        lines.append('    RewriteEngine On')
        lines.append('    RewriteCond %{HTTPS} off')
        lines.append('    RewriteRule ^(.*)$ https://%{HTTP_HOST}$1 [R=301,L]')
        lines.append('</VirtualHost>')

    return '\n'.join(lines)


def generate_proxy_vhost(vhost):
    lines = [
        f'# Generated by apache-vhost-manager on {datetime.utcnow().isoformat()}',
        f'<VirtualHost *:{vhost.listen_port}>',
    ]
    lines.extend(_server_name_block(vhost))
    lines.extend(_common_directives(vhost))
    lines.extend(_ssl_directives(vhost))

    if vhost.preserve_host:
        lines.append('    ProxyPreserveHost On')

    backend_url = f'{vhost.backend_protocol}://{vhost.backend_host}:{vhost.backend_port}{vhost.backend_path}'
    lines.append(f'    ProxyPass {vhost.proxy_path} {backend_url}')
    lines.append(f'    ProxyPassReverse {vhost.proxy_path} {backend_url}')

    if vhost.websocket_support:
        ws_url = f'ws://{vhost.backend_host}:{vhost.backend_port}{vhost.backend_path}'
        wss_url = f'wss://{vhost.backend_host}:{vhost.backend_port}{vhost.backend_path}'
        lines.append('    RewriteEngine On')
        lines.append('    RewriteCond %{HTTP:Upgrade} websocket [NC]')
        lines.append('    RewriteCond %{HTTP:Connection} upgrade [NC]')
        lines.append(f'    RewriteRule ^/?(.*) "{ws_url}$1" [P,L]')

    if vhost.proxy_timeout:
        lines.append(f'    ProxyTimeout {vhost.proxy_timeout}')

    # Request headers
    if vhost.proxy_headers:
        for header_line in vhost.proxy_headers.splitlines():
            header_line = header_line.strip()
            if header_line:
                lines.append(f'    RequestHeader {header_line}')

    # Response headers
    if vhost.response_headers:
        for header_line in vhost.response_headers.splitlines():
            header_line = header_line.strip()
            if header_line:
                lines.append(f'    Header {header_line}')

    if vhost.extra_security_headers:
        lines.append('    Header always set X-Frame-Options "SAMEORIGIN"')
        lines.append('    Header always set X-Content-Type-Options "nosniff"')
        lines.append('    Header always set Referrer-Policy "strict-origin-when-cross-origin"')

    if vhost.extra_directives:
        for directive in vhost.extra_directives.splitlines():
            lines.append(f'    {directive.strip()}')

    lines.append('</VirtualHost>')

    # HTTP to HTTPS redirect vhost
    if vhost.force_https and vhost.ssl_enabled:
        lines.append('')
        lines.append(f'<VirtualHost *:{vhost.listen_port}>')
        lines.extend(_server_name_block(vhost))
        lines.append('    RewriteEngine On')
        lines.append('    RewriteCond %{HTTPS} off')
        lines.append('    RewriteRule ^(.*)$ https://%{HTTP_HOST}$1 [R=301,L]')
        lines.append('</VirtualHost>')

    return '\n'.join(lines)


def generate_redirect_vhost(vhost):
    redirect_type = 'permanent' if vhost.redirect_permanent else 'temp'
    lines = [
        f'# Generated by apache-vhost-manager on {datetime.utcnow().isoformat()}',
        f'<VirtualHost *:{vhost.listen_port}>',
    ]
    lines.extend(_server_name_block(vhost))
    lines.extend(_common_directives(vhost))
    lines.extend(_ssl_directives(vhost))
    lines.append(f'    Redirect {redirect_type} "/" "{vhost.redirect_url}"')

    if vhost.extra_directives:
        for directive in vhost.extra_directives.splitlines():
            lines.append(f'    {directive.strip()}')

    lines.append('</VirtualHost>')
    return '\n'.join(lines)


def generate_config(vhost):
    if vhost.vhost_type == 'static':
        return generate_static_vhost(vhost)
    elif vhost.vhost_type == 'proxy':
        return generate_proxy_vhost(vhost)
    elif vhost.vhost_type == 'redirect':
        return generate_redirect_vhost(vhost)
    else:
        raise ValueError(f'Unknown vhost type: {vhost.vhost_type}')

